version: 2
registries:
  github-private:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GO_MODULES_TOKEN }}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries:
      - github-private
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      k8s-io:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
          - "github.com/aws/smithy-go"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/server/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
