#!/usr/bin/env bash
#
# Copyright Datadatdat.

#
# Utility script used during the docker build process to download and extract ZFS userland, using the same shell
# methods as are used at runtime.
#

source $(dirname $0)/zfs.sh
source $(dirname $0)/util.sh

set -xe

zfs_version=$(get_zfs_build_version)

# Use local file from git repository
local_file="/datadatdat/assets/zfs-$zfs_version-userland.tar.gz"
if [[ -f "$local_file" ]]; then
    echo "Using local ZFS userland file: $local_file"
    cp "$local_file" /var/tmp/userland.tar.gz
else
    log_error "Local ZFS userland file not found: $local_file"
fi

cd / && tar --skip-old-files -xvzf /var/tmp/userland.tar.gz
rm /var/tmp/userland.tar.gz
