#!/usr/bin/env bash
# Copyright Dit 2026
# SPDX-License-Identifier: BUSL-1.1
#

#
# Entry point for running a kubernetes operation. See KubernetesRunner for how this works. We expect the DIT_PATH
# environment variable to point to the base path for volumes and configuration, which is then passed to the runner.
#

exec java -DbasePath=$DIT_PATH -cp /dit/dit-server.jar dev.dit.context.kubernetes.KubernetesRunnerKt

